steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "pull"
      - "docker.io/abhinavtanwar/tanwar-flask-backend:latest" # Pulling the image from Docker Hub

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "instances"
      - "update-container"
      - "abhinav-flask-backend-instance"
      - "--zone"
      - "northamerica-northeast2-a"  # Replace with the correct zone where your instance is deployed
      - "--container-image"
      - "docker.io/abhinavtanwar/tanwar-flask-backend:latest" # Using Docker Hub image directly

options:
  logging: CLOUD_LOGGING_ONLY
